import { useRef, useCallback, useEffect } from 'react';
import { Language } from '../types';

const versesOfTheDay = {
    pt: [
        // Originais
        { book: 'João', chapter: 3, verse: 16, text: "Porque Deus amou o mundo de tal maneira que deu o seu Filho unigênito, para que todo aquele que nele crê не pereça, mas tenha a vida eterna.", reflection: "Este versículo é o coração do Evangelho. Ele nos lembra do amor incondicional de Deus, um amor tão grande que o levou a fazer o sacrifício supremo por nós. Que possamos viver hoje na certeza desse amor que nos salva e nos dá esperança." },
        { book: 'Jeremias', chapter: 29, verse: 11, text: "Porque eu bem sei os pensamentos que tenho a vosso respeito, diz o Senhor; pensamentos de paz, e não de mal, para vos dar o fim que esperais.", reflection: "Em meio às incertezas, Deus nos assegura que Seus planos para nós são de esperança e de um futuro próspero. Confie que Ele está no controle, mesmo quando o caminho parece escuro. Seus pensamentos são sempre para o nosso bem." },
        { book: 'Filipenses', chapter: 4, verse: 13, text: "Posso todas as coisas em Cristo que me fortalece.", reflection: "Esta é uma poderosa declaração de dependência e confiança. Nossa força не vem de nós mesmos, mas de Cristo. Hoje, enfrente seus desafios com a certeza de que a força de Deus está disponível para você em qualquer circunstância." },
        { book: 'Provérbios', chapter: 3, verse: 5, text: "Confia no Senhor de todo o teu coração, e não te estribes no teu próprio entendimento.", reflection: "A sabedoria humana é limitada, mas a de Deus é infinita. Este provérbio nos chama a uma entrega total, a confiar em Deus completamente, mesmo quando não entendemos Seus caminhos. A verdadeira paz vem da confiança, não do controle." },
        { book: 'Romanos', chapter: 8, verse: 28, text: "E sabemos que todas as coisas contribuem juntamente para o bem daqueles que amam a Deus, daqueles que são chamados segundo o seu propósito.", reflection: "Esta promessa nos dá conforto em meio às provações. Deus é soberano e pode usar até mesmo as situações mais difíceis para cumprir Seu propósito em nossas vidas. Mantenha a fé, pois Ele está tecendo uma bela tapeçaria com todos os fios da sua vida." },
        { book: 'Isaías', chapter: 41, verse: 10, text: "Não temas, porque eu sou contigo; не te assombres, porque eu sou o teu Deus; eu te fortaleço, e te ajudo, e te sustento com a destra da minha justiça.", reflection: "Esta é uma das mais belas promessas de companhia e proteção. Em momentos de medo ou fraqueza, lembre-se de que você não está só. O Criador do universo está ao seu lado, oferecendo força, ajuda e sustento." },
        { book: 'Salmos', chapter: 23, verse: 1, text: "O Senhor é o meu pastor; nada me faltará.", reflection: "A imagem de Deus como nosso pastor evoca cuidado, provisão e orientação. Viver com essa certeza nos liberta da ansiedade sobre o futuro e nos permite descansar na Sua soberania e bondade." },
        { book: 'Mateus', chapter: 11, verse: 28, text: "Vinde a mim, todos os que estais cansados e oprimidos, e eu vos aliviarei.", reflection: "Jesus oferece um convite aberto a todos que se sentem sobrecarregados. Ele não promete uma vida sem fardos, mas oferece Seu jugo, que é suave, e Seu alívio para a nossa alma. Entregue a Ele hoje o seu cansaço." },
        { book: '2 Coríntios', chapter: 5, verse: 17, text: "Assim que, se alguém está em Cristo, nova criatura é; as coisas velhas já passaram; eis que tudo se fez novo.", reflection: "A fé em Cristo é transformadora. Ela não apenas perdoa nosso passado, mas nos recria, nos dando uma nova identidade e um novo propósito. Viva hoje como a nova criatura que você é em Jesus." },
        { book: 'Gálatas', chapter: 5, verse: 22, text: "Mas o fruto do Espírito é: amor, gozo, paz, longanimidade, benignidade, bondade, fé, mansidão, temperança.", reflection: "Estas não são qualidades que produzimos por nosso próprio esforço, mas o resultado natural da presença do Espírito Santo em nós. Que possamos cultivar uma vida que permita a este fruto crescer e abençoar a todos ao nosso redor." },
        // Novos versículos
        { book: 'Josué', chapter: 1, verse: 9, text: "Não to mandei eu? Esforça-te, e tem bom ânimo; não pasmes, nem te espantes; porque o Senhor teu Deus é contigo, por onde quer que andares.", reflection: "Este é um chamado à coragem que se baseia na presença constante de Deus. Em cada passo, em cada desafio, Ele está conosco. Viva com ousadia, pois sua força não está em você, mas Naquele que o acompanha." },
        { book: 'Salmos', chapter: 119, verse: 105, text: "Lâmpada para os meus pés é tua palavra, e luz para o meu caminho.", reflection: "A Palavra de Deus é nossa guia segura na escuridão e na incerteza. Que ela ilumine suas decisões hoje, mostrando não apenas o próximo passo, mas também a direção a seguir." },
        { book: 'Mateus', chapter: 6, verse: 33, text: "Mas, buscai primeiro o reino de Deus, e a sua justiça, e todas estas coisas vos serão acrescentadas.", reflection: "Jesus nos ensina a principal prioridade da vida: buscar a Deus acima de tudo. Quando nosso coração está alinhado com o dEle, Ele cuida de todas as nossas outras necessidades. Coloque Deus em primeiro lugar hoje." },
        { book: '2 Timóteo', chapter: 1, verse: 7, text: "Porque Deus não nos deu o espírito de temor, mas de fortaleza, e de amor, e de moderação.", reflection: "O medo não vem de Deus. Ele nos capacita com poder para superar, amor para nos conectar e uma mente sã para decidir. Rejeite o medo e abrace a força que Ele lhe deu." },
        { book: 'Hebreus', chapter: 11, verse: 1, text: "Ora, a fé é o firme fundamento das coisas que se esperam, e a prova das coisas que se não vêem.", reflection: "Fé não é um salto no escuro, mas um passo firme na luz da promessa de Deus. É a certeza em nosso coração do que nossos olhos ainda não podem ver. Viva pela fé, não pela vista." },
        { book: 'Efésios', chapter: 2, verse: 8, text: "Porque pela graça sois salvos, por meio da fé; e isto не vem de vós, é dom de Deus.", reflection: "Nossa salvação é um presente, não uma conquista. Ela nasce do amor de Deus (graça) e é recebida por nossa confiança (fé). Descanse na segurança deste presente imerecido." },
        { book: '1 Pedro', chapter: 5, verse: 7, text: "Lançando sobre ele toda a vossa ansiedade, porque ele tem cuidado de vós.", reflection: "Deus nos convida a entregar a Ele o peso de nossas preocupações. Ele não é indiferente à sua luta; Ele se importa profundamente. Confie seus fardos a Ele e experimente o Seu cuidado." },
        { book: 'Romanos', chapter: 12, verse: 2, text: "E não vos conformeis com este mundo, mas transformai-vos pela renovação do vosso entendimento, para que experimenteis qual seja a boa, agradável, e perfeita vontade de Deus.", reflection: "A verdadeira transformação começa na mente. Ao permitir que Deus renove nossos pensamentos, começamos a ver o mundo e a nós mesmos através de Seus olhos, discernindo Sua vontade perfeita." },
        { book: 'Deuteronômio', chapter: 31, verse: 6, text: "Esforçai-vos, e animai-vos; não temais, nem vos espanteis diante deles; porque o Senhor vosso Deus é o que vai convosco; não vos deixará nem vos desamparará.", reflection: "A promessa da companhia infalível de Deus é o maior antídoto contra o medo. Ele não apenas vai conosco, Ele luta por nós. Não há razão para temer o que está à frente." },
        { book: 'Salmos', chapter: 46, verse: 1, text: "Deus é o nosso refúgio e fortaleza, socorro bem presente na angústia.", reflection: "Nos tempos de crise, temos um porto seguro. Deus не é um socorro distante; Ele está presente, aqui e agora, pronto para nos proteger e fortalecer." },
        { book: 'João', chapter: 14, verse: 27, text: "Deixo-vos a paz, a minha paz vos dou; не vo-la dou como o mundo a dá. Não se turbe o vosso coração, nem se atemorize.", reflection: "A paz que Jesus oferece não é a ausência de problemas, mas a presença de Deus em meio a eles. É uma paz que acalma a alma e guarda o coração, independentemente das circunstâncias." },
        { book: 'Salmos', chapter: 37, verse: 4, text: "Deleita-te também no Senhor, e te concederá os desejos do teu coração.", reflection: "Quando encontramos nossa maior alegria em Deus, nossos desejos começam a se alinhar com os dEle. A verdadeira satisfação não está em ter o que queremos, mas em querer Aquele que nos tem." },
        { book: 'João', chapter: 16, verse: 33, text: "Tenho-vos dito isto, para que em mim tenhais paz; no mundo tereis aflições, mas tende bom ânimo, eu venci o mundo.", reflection: "Jesus é honesto sobre as dificuldades da vida, mas nos dá uma esperança maior. Sua vitória sobre o mundo nos garante que, Nele, nossas aflições são temporárias e a vitória final é certa." },
        { book: 'Romanos', chapter: 15, verse: 13, text: "Ora o Deus de esperança vos encha de todo o gozo e paz em crença, para que abundeis em esperança pela virtude do Espírito Santo.", reflection: "A esperança cristã não é um mero otimismo, mas uma alegria e paz profundas que vêm de confiar em Deus. É um dom do Espírito Santo que transborda em nós, mesmo em meio às dificuldades." },
        { book: 'Colossenses', chapter: 3, verse: 23, text: "E tudo quanto fizerdes, fazei-o de todo o coração, como ao Senhor, e não aos homens.", reflection: "Nosso trabalho, seja qual for, ganha um propósito eterno quando o fazemos para Deus. Ele transforma o mundano em sagrado e nos motiva a dar o nosso melhor, не por aplausos, mas por amor." },
        { book: 'Isaías', chapter: 40, verse: 31, text: "Mas os que esperam no Senhor renovarão as forças, subirão com asas como águias; correrão, e não se cansarão; caminharão, e не se fatigarão.", reflection: "Esperar em Deus não é passividade, mas uma troca ativa de nossa fraqueza pela Sua força infinita. É essa confiança que nos permite voar acima das tempestades da vida." },
        { book: 'Salmos', chapter: 91, verse: 1, text: "Aquele que habita no esconderijo do Altíssimo, à sombra do Onipotente descansará.", reflection: "Há um lugar de segurança e paz perfeita disponível para nós: a presença de Deus. Habitar com Ele significa viver em constante comunhão, encontrando descanso sob Sua proteção soberana." },
        { book: 'Mateus', chapter: 7, verse: 7, text: "Pedi, e dar-se-vos-á; buscai, e encontrareis; batei, e abrir-se-vos-á.", reflection: "Deus se deleita em responder às orações de Seus filhos. Este versículo é um convite à persistência na oração, com a confiança de que temos um Pai que ouve e responde." },
        { book: 'Tiago', chapter: 1, verse: 12, text: "Bem-aventurado o homem que suporta a tentação; porque, quando for provado, receberá a coroa da vida, a qual o Senhor tem prometido aos que o amam.", reflection: "As provações não são para nos destruir, mas para nos refinar. A perseverança em meio às dificuldades revela a genuinidade da nossa fé e nos qualifica para a recompensa eterna prometida por Deus." },
        { book: 'Miquéias', chapter: 6, verse: 8, text: "Ele te declarou, ó homem, o que é bom; e que é o que o Senhor pede de ti, senão que pratiques a justiça, e ames a benignidade, e andes humildemente com o teu Deus?", reflection: "A essência do que Deus deseja de nós não está em rituais complexos, mas em um coração transformado que se manifesta em ações justas, amor misericordioso e uma caminhada humilde com Ele." }
    ],
    en: [
        // Originals
        { book: 'John', chapter: 3, verse: 16, text: "For God so loved the world, that he gave his only begotten Son, that whosoever believeth in him should not perish, but have everlasting life.", reflection: "This verse is the heart of the Gospel. It reminds us of God's unconditional love, a love so great that it led Him to make the ultimate sacrifice for us. May we live today in the certainty of this love that saves us and gives us hope." },
        { book: 'Jeremiah', chapter: 29, verse: 11, text: "For I know the thoughts that I think toward you, saith the Lord, thoughts of peace, and not of evil, to give you an expected end.", reflection: "Amidst uncertainties, God assures us that His plans for us are of hope and a prosperous future. Trust that He is in control, even when the path seems dark. His thoughts are always for our good." },
        { book: 'Philippians', chapter: 4, verse: 13, text: "I can do all things through Christ which strengtheneth me.", reflection: "This is a powerful declaration of dependence and trust. Our strength comes not from ourselves, but from Christ. Today, face your challenges with the assurance that God's strength is available to you in any circumstance." },
        { book: 'Proverbs', chapter: 3, verse: 5, text: "Trust in the Lord with all thine heart; and lean not unto thine own understanding.", reflection: "Human wisdom is limited, but God's is infinite. This proverb calls us to total surrender, to trust God completely, even when we do not understand His ways. True peace comes from trust, not control." },
        { book: 'Romans', chapter: 8, verse: 28, text: "And we know that all things work together for good to them that love God, to them who are the called according to his purpose.", reflection: "This promise gives us comfort in the midst of trials. God is sovereign and can use even the most difficult situations to fulfill His purpose in our lives. Keep the faith, for He is weaving a beautiful tapestry with all the threads of your life." },
        { book: 'Isaiah', chapter: 41, verse: 10, text: "Fear thou not; for I am with thee: be not dismayed; for I am thy God: I will strengthen thee; yea, I will help thee; yea, I will uphold thee with the right hand of my righteousness.", reflection: "This is one of the most beautiful promises of companionship and protection. In times of fear or weakness, remember that you are not alone. The Creator of the universe is by your side, offering strength, help, and support." },
        { book: 'Psalm', chapter: 23, verse: 1, text: "The Lord is my shepherd; I shall not want.", reflection: "The image of God as our shepherd evokes care, provision, and guidance. Living with this assurance frees us from anxiety about the future and allows us to rest in His sovereignty and goodness." },
        { book: 'Matthew', chapter: 11, verse: 28, text: "Come unto me, all ye that labour and are heavy laden, and I will give you rest.", reflection: "Jesus offers an open invitation to all who feel overburdened. He does not promise a life without burdens, but He offers His yoke, which is easy, and His rest for our souls. Surrender your weariness to Him today." },
        { book: '2 Corinthians', chapter: 5, verse: 17, text: "Therefore if any man be in Christ, he is a new creature: old things are passed away; behold, all things are become new.", reflection: "Faith in Christ is transformative. It not only forgives our past but recreates us, giving us a new identity and a new purpose. Live today as the new creature you are in Jesus." },
        { book: 'Galatians', chapter: 5, verse: 22, text: "But the fruit of the Spirit is love, joy, peace, longsuffering, gentleness, goodness, faith, meekness, temperance.", reflection: "These are not qualities we produce by our own effort, but the natural result of the Holy Spirit's presence in us. May we cultivate a life that allows this fruit to grow and bless all those around us." },
        // New Verses
        { book: 'Joshua', chapter: 1, verse: 9, text: "Have not I commanded thee? Be strong and of a good courage; be not afraid, neither be thou dismayed: for the Lord thy God is with thee whithersoever thou goest.", reflection: "This is a call to courage based on God's constant presence. In every step, in every challenge, He is with us. Live boldly, for your strength is not in yourself, but in Him who accompanies you." },
        { book: 'Psalm', chapter: 119, verse: 105, text: "Thy word is a lamp unto my feet, and a light unto my path.", reflection: "God's Word is our sure guide in darkness and uncertainty. Let it illuminate your decisions today, showing not only the next step, but also the direction to follow." },
        { book: 'Matthew', chapter: 6, verse: 33, text: "But seek ye first the kingdom of God, and his righteousness; and all these things shall be added unto you.", reflection: "Jesus teaches us the main priority of life: to seek God above all else. When our heart is aligned with His, He takes care of all our other needs. Put God first today." },
        { book: '2 Timothy', chapter: 1, verse: 7, text: "For God hath not given us the spirit of fear; but of power, and of love, and of a sound mind.", reflection: "Fear does not come from God. He empowers us with strength to overcome, love to connect, and a sound mind to decide. Reject fear and embrace the strength He has given you." },
        { book: 'Hebrews', chapter: 11, verse: 1, text: "Now faith is the substance of things hoped for, the evidence of things not seen.", reflection: "Faith is not a leap in the dark, but a firm step in the light of God's promise. It is the assurance in our hearts of what our eyes cannot yet see. Live by faith, not by sight." },
        { book: 'Ephesians', chapter: 2, verse: 8, text: "For by grace are ye saved through faith; and that not of yourselves: it is the gift of God.", reflection: "Our salvation is a gift, not an achievement. It is born of God's love (grace) and received by our trust (faith). Rest in the security of this unmerited gift." },
        { book: '1 Peter', chapter: 5, verse: 7, text: "Casting all your care upon him; for he careth for you.", reflection: "God invites us to hand over the weight of our worries to Him. He is not indifferent to your struggle; He cares deeply. Entrust your burdens to Him and experience His care." },
        { book: 'Romans', chapter: 12, verse: 2, text: "And be not conformed to this world: but be ye transformed by the renewing of your mind, that ye may prove what is that good, and acceptable, and perfect, will of God.", reflection: "True transformation begins in the mind. By allowing God to renew our thoughts, we begin to see the world and ourselves through His eyes, discerning His perfect will." },
        { book: 'Deuteronomy', chapter: 31, verse: 6, text: "Be strong and of a good courage, fear not, nor be afraid of them: for the Lord thy God, he it is that doth go with thee; he will not fail thee, nor forsake thee.", reflection: "The promise of God's unfailing companionship is the greatest antidote to fear. He not only goes with us, He fights for us. There is no reason to fear what lies ahead." },
        { book: 'Psalm', chapter: 46, verse: 1, text: "God is our refuge and strength, a very present help in trouble.", reflection: "In times of crisis, we have a safe harbor. God is not a distant help; He is present, here and now, ready to protect and strengthen us." },
        { book: 'John', chapter: 14, verse: 27, text: "Peace I leave with you, my peace I give unto you: not as the world giveth, give I unto you. Let not your heart be troubled, neither let it be afraid.", reflection: "The peace Jesus offers is not the absence of problems, but the presence of God amidst them. It's a peace that calms the soul and guards the heart, regardless of circumstances." },
        { book: 'Psalm', chapter: 37, verse: 4, text: "Delight thyself also in the Lord: and he shall give thee the desires of thine heart.", reflection: "When we find our greatest joy in God, our desires begin to align with His. True satisfaction is not in getting what we want, but in wanting the One who has us." },
        { book: 'John', chapter: 16, verse: 33, text: "These things I have spoken unto you, that in me ye might have peace. In the world ye shall have tribulation: but be of good cheer; I have overcome the world.", reflection: "Jesus is honest about life's hardships, but He gives us a greater hope. His victory over the world assures us that, in Him, our afflictions are temporary and the final victory is certain." },
        { book: 'Romans', chapter: 15, verse: 13, text: "Now the God of hope fill you with all joy and peace in believing, that ye may abound in hope, through the power of the Holy Ghost.", reflection: "Christian hope is not mere optimism, but a deep joy and peace that come from trusting God. It is a gift of the Holy Spirit that overflows in us, even in the midst of difficulties." },
        { book: 'Colossians', chapter: 3, verse: 23, text: "And whatsoever ye do, do it heartily, as to the Lord, and not unto men;", reflection: "Our work, whatever it may be, gains an eternal purpose when we do it for God. It transforms the mundane into the sacred and motivates us to give our best, not for applause, but for love." },
        { book: 'Isaiah', chapter: 40, verse: 31, text: "But they that wait upon the Lord shall renew their strength; they shall mount up with wings as eagles; they shall run, and not be weary; and they shall walk, and not faint.", reflection: "Waiting on God is not passive, but an active exchange of our weakness for His infinite strength. It is this trust that allows us to soar above life's storms." },
        { book: 'Psalm', chapter: 91, verse: 1, text: "He that dwelleth in the secret place of the most High shall abide under the shadow of the Almighty.", reflection: "There is a place of perfect safety and peace available to us: the presence of God. To dwell with Him means to live in constant communion, finding rest under His sovereign protection." },
        { book: 'Matthew', chapter: 7, verse: 7, text: "Ask, and it shall be given you; seek, and ye shall find; knock, and it shall be opened unto you:", reflection: "God delights in answering the prayers of His children. This verse is an invitation to persistence in prayer, with the confidence that we have a Father who hears and responds." },
        { book: 'James', chapter: 1, verse: 12, text: "Blessed is the man that endureth temptation: for when he is tried, he shall receive the crown of life, which the Lord hath promised to them that love him.", reflection: "Trials are not meant to destroy us, but to refine us. Perseverance through hardship reveals the genuineness of our faith and qualifies us for the eternal reward promised by God." },
        { book: 'Micah', chapter: 6, verse: 8, text: "He hath shewed thee, O man, what is good; and what doth the Lord require of thee, but to do justly, and to love mercy, and to walk humbly with thy God?", reflection: "The essence of what God desires from us is not in complex rituals, but in a transformed heart that manifests in just actions, merciful love, and a humble walk with Him." }
    ],
    es: [
        // Originales
        { book: 'Juan', chapter: 3, verse: 16, text: "Porque de tal manera amó Dios al mundo, que ha dado a su Hijo unigénito, para que todo aquel que en él cree, no se pierda, mas tenga vida eterna.", reflection: "Este versículo es el corazón del Evangelio. Nos recuerda el amor incondicional de Dios, un amor tan grande que lo llevó a hacer el sacrificio supremo por nosotros. Que podamos vivir hoy en la certeza de este amor que nos salva y nos da esperanza." },
        { book: 'Jeremías', chapter: 29, verse: 11, text: "Porque yo sé los pensamientos que tengo acerca de vosotros, dice Jehová, pensamientos de paz, y no de mal, para daros el fin que esperáis.", reflection: "En medio de las incertidumbres, Dios nos asegura que Sus planes para nosotros son de esperanza y un futuro próspero. Confía en que Él está en control, incluso cuando el camino parece oscuro. Sus pensamientos son siempre para nuestro bien." },
        { book: 'Filipenses', chapter: 4, verse: 13, text: "Todo lo puedo en Cristo que me fortalece.", reflection: "Esta es una poderosa declaración de dependencia y confianza. Nuestra fuerza no proviene de nosotros mismos, sino de Cristo. Hoy, enfrenta tus desafíos con la certeza de que la fortaleza de Dios está disponible para ti en cualquier circunstancia." },
        { book: 'Proverbios', chapter: 3, verse: 5, text: "Fíate de Jehová de todo tu corazón, Y no te apoyes en tu propia prudencia.", reflection: "La sabiduría humana es limitada, pero la de Dios es infinita. Este proverbio nos llama a una entrega total, a confiar en Dios completamente, incluso cuando no entendemos Sus caminos. La verdadera paz viene de la confianza, no del control." },
        { book: 'Romanos', chapter: 8, verse: 28, text: "Y sabemos que a los que aman a Dios, todas las cosas les ayudan a bien, esto es, a los que conforme a su propósito son llamados.", reflection: "Esta promesa nos da consuelo en medio de las pruebas. Dios es soberano y puede usar incluso las situaciones más difíciles para cumplir Su propósito en nuestras vidas. Mantén la fe, porque Él está tejiendo un hermoso tapiz con todos los hilos de tu vida." },
        { book: 'Isaías', chapter: 41, verse: 10, text: "No temas, porque yo estoy contigo; no desmayes, porque yo soy tu Dios que te esfuerzo; siempre te ayudaré, siempre te sustentaré con la diestra de mi justicia.", reflection: "Esta es una de las más hermosas promesas de compañía y protección. En momentos de miedo o debilidad, recuerda que no estás solo. El Creador del universo está a tu lado, ofreciéndote fuerza, ayuda y sustento." },
        { book: 'Salmos', chapter: 23, verse: 1, text: "Jehová es mi pastor; nada me faltará.", reflection: "La imagen de Dios como nuestro pastor evoca cuidado, provisión y guía. Vivir con esta certeza nos libera de la ansiedad por el futuro y nos permite descansar en Su soberanía y bondad." },
        { book: 'Mateo', chapter: 11, verse: 28, text: "Venid a mí todos los que estáis trabajados y cargados, y yo os haré descansar.", reflection: "Jesús ofrece una invitación abierta a todos los que se sienten abrumados. No promete una vida sin cargas, pero ofrece Su yugo, que es fácil, y Su descanso para nuestras almas. Entrégale hoy tu cansancio." },
        { book: '2 Corintios', chapter: 5, verse: 17, text: "De modo que si alguno está en Cristo, nueva criatura es; las cosas viejas pasaron; he aquí todas son hechas nuevas.", reflection: "La fe en Cristo es transformadora. No solo perdona nuestro pasado, sino que nos recrea, dándonos una nueva identidad y un nuevo propósito. Vive hoy como la nueva criatura que eres en Jesús." },
        { book: 'Gálatas', chapter: 5, verse: 22, text: "Mas el fruto del Espíritu es amor, gozo, paz, paciencia, benignidad, bondad, fe, mansedumbre, templanza.", reflection: "Estas no son cualidades que producimos por nuestro propio esfuerzo, sino el resultado natural de la presencia del Espíritu Santo en nosotros. Que podamos cultivar una vida que permita que este fruto crezca y bendiga a todos los que nos rodean." },
        // Nuevos Versículos
        { book: 'Josué', chapter: 1, verse: 9, text: "¿No te he mandado que te esfuerces y seas valiente? No temas ni desmayes, porque Jehová tu Dios estará contigo en dondequiera que vayas.", reflection: "Este es un llamado al coraje que se basa en la presencia constante de Dios. En cada paso, en cada desafío, Él está con nosotros. Vive con audacia, porque tu fuerza no está en ti, sino en Aquel que te acompaña." },
        { book: 'Salmos', chapter: 119, verse: 105, text: "Lámpara es a mis pies tu palabra, Y lumbrera a mi camino.", reflection: "La Palabra de Dios es nuestra guía segura en la oscuridad y la incertidumbre. Que ella ilumine tus decisiones hoy, mostrando no solo el siguiente paso, sino también la dirección a seguir." },
        { book: 'Mateo', chapter: 6, verse: 33, text: "Mas buscad primeramente el reino de Dios y su justicia, y todas estas cosas os serán añadidas.", reflection: "Jesús nos enseña la principal prioridad de la vida: buscar a Dios por encima de todo. Cuando nuestro corazón está alineado con el Suyo, Él cuida de todas nuestras otras necesidades. Pon a Dios en primer lugar hoy." },
        { book: '2 Timoteo', chapter: 1, verse: 7, text: "Porque no nos ha dado Dios espíritu de cobardía, sino de poder, de amor y de dominio propio.", reflection: "El miedo no viene de Dios. Él nos capacita con poder para superar, amor para conectar y una mente sana para decidir. Rechaza el miedo y abraza la fuerza que Él te ha dado." },
        { book: 'Hebreos', chapter: 11, verse: 1, text: "Es, pues, la fe la certeza de lo que se espera, la convicción de lo que no se ve.", reflection: "La fe no es un salto en la oscuridad, sino un paso firme en la luz de la promesa de Dios. Es la seguridad en nuestro corazón de lo que nuestros ojos aún no pueden ver. Vive por fe, no por vista." },
        { book: 'Efesios', chapter: 2, verse: 8, text: "Porque por gracia sois salvos por medio de la fe; y esto no de vosotros, pues es don de Dios.", reflection: "Nuestra salvación es un regalo, no un logro. Nace del amor de Dios (gracia) y se recibe por nuestra confianza (fe). Descansa en la seguridad de este regalo inmerecido." },
        { book: '1 Pedro', chapter: 5, verse: 7, text: "echando toda vuestra ansiedad sobre él, porque él tiene cuidado de vosotros.", reflection: "Dios nos invita a entregarle el peso de nuestras preocupaciones. Él no es indiferente a tu lucha; Él se preocupa profundamente. Confía tus cargas a Él y experimenta Su cuidado." },
        { book: 'Romanos', chapter: 12, verse: 2, text: "No os conforméis a este siglo, sino transformaos por medio de la renovación de vuestro entendimiento, para que comprobéis cuál sea la buena voluntad de Dios, agradable y perfecta.", reflection: "La verdadera transformación comienza en la mente. Al permitir que Dios renueve nuestros pensamientos, comenzamos a ver el mundo y a nosotros mismos a través de Sus ojos, discerniendo Su voluntad perfecta." },
        { book: 'Deuteronomio', chapter: 31, verse: 6, text: "Esforzaos y cobrad ánimo; no temáis, ni tengáis miedo de ellos, porque Jehová tu Dios es el que va contigo; no te dejará, ni te desamparará.", reflection: "La promesa de la compañía infalible de Dios es el mayor antídoto contra el miedo. Él no solo va con nosotros, Él lucha por nosotros. No hay razón para temer lo que está por delante." },
        { book: 'Salmos', chapter: 46, verse: 1, text: "Dios es nuestro amparo y fortaleza, Nuestro pronto auxilio en las tribulaciones.", reflection: "En tiempos de crisis, tenemos un puerto seguro. Dios no es una ayuda lejana; Él está presente, aquí y ahora, listo para protegernos y fortalecernos." },
        { book: 'Juan', chapter: 14, verse: 27, text: "La paz os dejo, mi paz os doy; yo no os la doy como el mundo la da. No se turbe vuestro corazón, ni tenga miedo.", reflection: "La paz que Jesús ofrece no es la ausencia de problemas, sino la presencia de Dios en medio de ellos. Es una paz que calma el alma y guarda el corazón, independientemente de las circunstancias." },
        { book: 'Salmos', chapter: 37, verse: 4, text: "Deléitate asimismo en Jehová, Y él te concederá las peticiones de tu corazón.", reflection: "Cuando encontramos nuestra mayor alegría en Dios, nuestros deseos comienzan a alinearse con los Suyos. La verdadera satisfacción no está en tener lo que queremos, sino en querer a Aquel que nos tiene." },
        { book: 'Juan', chapter: 16, verse: 33, text: "Estas cosas os he hablado para que en mí tengáis paz. En el mundo tendréis aflicción; pero confiad, yo he vencido al mundo.", reflection: "Jesús es honesto sobre las dificultades de la vida, pero nos da una esperanza mayor. Su victoria sobre el mundo nos asegura que, en Él, nuestras aflicciones son temporales y la victoria final es cierta." },
        { book: 'Romanos', chapter: 15, verse: 13, text: "Y el Dios de esperanza os llene de todo gozo y paz en el creer, para que abundéis en esperanza por el poder del Espíritu Santo.", reflection: "La esperanza cristiana no es un mero optimismo, sino un gozo y paz profundos que provienen de confiar en Dios. Es un don del Espíritu Santo que rebosa en nosotros, incluso en medio de las dificultades." },
        { book: 'Colosenses', chapter: 3, verse: 23, text: "Y todo lo que hagáis, hacedlo de corazón, como para el Señor y no para los hombres;", reflection: "Nuestro trabajo, sea cual sea, adquiere un propósito eterno cuando lo hacemos para Dios. Transforma lo mundano en sagrado y nos motiva a dar lo mejor de nosotros, no por aplausos, sino por amor." },
        { book: 'Isaías', chapter: 40, verse: 31, text: "pero los que esperan a Jehová tendrán nuevas fuerzas; levantarán alas como las águilas; correrán, y no se cansarán; caminarán, y no se fatigarán.", reflection: "Esperar en Dios no es pasividad, sino un intercambio activo de nuestra debilidad por Su fuerza infinita. Es esta confianza la que nos permite volar por encima de las tormentas de la vida." },
        { book: 'Salmos', chapter: 91, verse: 1, text: "El que habita al abrigo del Altísimo Morará bajo la sombra del Omnipotente.", reflection: "Hay un lugar de seguridad y paz perfecta disponible para nosotros: la presencia de Dios. Habitar con Él significa vivir en constante comunión, encontrando descanso bajo Su protección soberana." },
        { book: 'Mateo', chapter: 7, verse: 7, text: "Pedid, y se os dará; buscad, y hallaréis; llamad, y se os abrirá.", reflection: "Dios se deleita en responder las oraciones de Sus hijos. Este versículo es una invitación a la persistencia en la oración, con la confianza de que tenemos un Padre que oye y responde." },
        { book: 'Santiago', chapter: 1, verse: 12, text: "Bienaventurado el varón que soporta la tentación; porque cuando haya resistido la prueba, recibirá la corona de vida, que Dios ha prometido a los que le aman.", reflection: "Las pruebas no son para destruirnos, sino para refinarnos. La perseverancia en medio de las dificultades revela la autenticidad de nuestra fe y nos califica para la recompensa eterna prometida por Dios." },
        { book: 'Miqueas', chapter: 6, verse: 8, text: "Oh hombre, él te ha declarado lo que es bueno, y qué pide Jehová de ti: solamente hacer justicia, y amar misericordia, y humillarte ante tu Dios.", reflection: "La esencia de lo que Dios desea de nosotros no está en rituales complejos, sino en un corazón transformado que se manifiesta en acciones justas, amor misericordioso y un caminar humilde con Él." }
    ]
};

export const getTodaysVerse = (lang: Language) => {
    const today = new Date();
    const dayOfYear = Math.floor((today.getTime() - new Date(today.getFullYear(), 0, 0).getTime()) / (1000 * 60 * 60 * 24));
    const langVerses = versesOfTheDay[lang] || versesOfTheDay.pt;
    return langVerses[dayOfYear % langVerses.length];
};

export const useNotifications = () => {
    const notificationTimeoutRef = useRef<number | null>(null);

    const scheduleNotification = useCallback(async () => {
        if (notificationTimeoutRef.current) {
            clearTimeout(notificationTimeoutRef.current);
            notificationTimeoutRef.current = null;
        }

        const isEnabled = localStorage.getItem('notifications_enabled') === 'true';
        if (!isEnabled || typeof Notification === 'undefined' || Notification.permission !== 'granted') {
            return;
        }

        const time = localStorage.getItem('notification_time') || '08:00';
        const lang = (localStorage.getItem('semear_language') as Language) || 'pt';
        const [hours, minutes] = time.split(':').map(Number);
        
        const now = new Date();
        const notificationDate = new Date();
        notificationDate.setHours(hours, minutes, 0, 0);

        if (now > notificationDate) {
            notificationDate.setDate(notificationDate.getDate() + 1);
        }

        const timeToNotification = notificationDate.getTime() - now.getTime();

        notificationTimeoutRef.current = window.setTimeout(async () => {
            const verse = getTodaysVerse(lang);
            if (verse) {
                 new Notification(`${verse.book} ${verse.chapter}:${verse.verse}`, { 
                    body: verse.reflection,
                });
            }
            scheduleNotification(); // Re-schedule for the next day
        }, timeToNotification);

    }, []);

    useEffect(() => {
        scheduleNotification();
        const handleSettingsChange = () => scheduleNotification();
        
        window.addEventListener('storage', handleSettingsChange);
        window.addEventListener('settings-changed', handleSettingsChange);

        return () => {
            if (notificationTimeoutRef.current) clearTimeout(notificationTimeoutRef.current);
            window.removeEventListener('storage', handleSettingsChange);
            window.removeEventListener('settings-changed', handleSettingsChange);
        };
    }, [scheduleNotification]);
};
